routes/admin.php
<?php
 Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return Redirect('admin/dashboard');
});

Route::get('/dashboard', 'AdminController@dashboard');

//Chat
Route::get('/chat', 'AdminController@chat');
Route::post('/chat', 'AdminController@chat');	
Route::post('/user_friends', 'AdminController@user_friends');

//Push
Route::get('/push', 'AdminController@push');
Route::post('/push', 'AdminController@send_push');

//User report
Route::get('/user-report', 'AdminController@user_report');
Route::post('/user-block/{id}', 'AdminController@user_block');

//Payment
Route::get('user-premium', 'AdminController@user_premium');
Route::get('user-transaction', 'AdminController@user_transaction');
Route::get('admin-transaction', 'AdminController@admin_transaction');

//Resource
Route::resource('user', 	'Resource\UserResource');
Route::resource('interest', 	'Resource\InterestResource');
Route::resource('premium', 	'Resource\PremiumResource');

//Settings
Route::get('/settings', 'AdminController@adminSettings');
Route::post('/settings_store', 'AdminController@settings_store');

Route::get('/static_pages', 'AdminController@static_pages');
Route::post('/static_update', 'AdminController@static_update');

//Accounts
Route::get('/profile', 'AdminController@profile');
Route::post('/profile_update', 'AdminController@profile_update');

Route::get('/password', 'AdminController@password');
Route::post('/password_update', 'AdminController@password_update');

//Matches
Route::get('/matches', 'AdminController@user_matches');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('/otp', 'Auth\RegisterController@OTP');
Route::get('/', function () {
    //return view('welcome');
    $refercode=@$_GET['refercode'];
    Session::put('refercode',$refercode);
    return Redirect('/login');
});
/*Route::get('/home', function () {
    //return view('welcome');
    return Redirect('/dashboard');
});*/

//Static pages


Route::get('/clearconfig', function () {
    Artisan::call('config:clear');
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('config:cache');
    Artisan::call('view:clear');
});


Route::get('privacy', function () {
	$user=Auth::user();
	if($user)$user=$user;
	else $user=array();
    return view('privacy',compact('user'));
});
Route::get('terms', function () {
    $user=Auth::user();
	if($user)$user=$user;
	else $user=array();
    return view('terms',compact('user'));
});

Route::get('help', function () {
    
    $user=Auth::user();
    if($user)
      $user=$user;
    else 
      $user=array();
    return view('help',compact('user'));
});

// Route::get('contactus', function () {
//     $user=Auth::user();
// 	if($user)$user=$user;
// 	else $user=array();
//     return view('contactus',compact('user'));
// });

Route::get('testpush', 'SendPushNotification@testpush');

Auth::routes();

Route::group(['namespace' => 'Auth'], function() {
Route::post('/password/reset', 'ResetPasswordController@reset');
});

//Social login integration
Route::get('auth/facebook', 'Auth\SocialLoginController@redirectToFaceBook');
Route::get('auth/facebook/callback', 'Auth\SocialLoginController@handleFacebookCallback');
Route::get('auth/google', 'Auth\SocialLoginController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\SocialLoginController@handleGoogleCallback');
Route::get('auth/linkedin', 'Auth\SocialLoginController@redirectToLinkedin');
Route::get('auth/linkedin/callback', 'Auth\SocialLoginController@handleLinkedinCallback');
Route::post('account/kit', 'Auth\SocialLoginController@account_kit')->name('account.kit');

Route::get('/home', 'UserController@home');
Route::get('/dashboard', 'UserController@find_matches');
Route::get('/mapview', 'UserController@map_view');
Route::get('/profile', 'UserController@viewProfile');
Route::get('/editprofile', 'UserController@editProfile');
Route::post('/editprofile', 'UserController@updateProfile');
//ContactUs Details
Route::get('contactus', 'UserController@contactus');

Route::get('/matches', 'UserController@matches');
Route::get('/discover_settings', 'UserController@discover_settings');
Route::post('/discover_settings', 'UserController@update_discover_settings');
Route::get('/who_likes_me', 'UserController@who_likes_me');
Route::get('/chat', 'UserController@chat');
Route::get('/chat_user/{id}', 'UserController@chat_user');
//Route::get('/help', 'UserController@help');
Route::post('/likes' , 'UserController@likes');
Route::post('/update/new/notification' ,'UserController@update_notification');
Route::post('/skip' , 'UserController@skip');
Route::post('/update_likes' , 'UserController@update_likes');
Route::post('/single_user' , 'UserController@single_user');
Route::get('/payments', 'UserController@payment');
Route::post('/add_money', 'UserController@add_money');
Route::post('/payment_process', 'UserController@payment_process');
Route::get('/transaction_history', 'UserController@transaction_history');
Route::get('/notifications', 'UserController@notifications');
Route::get('/invites', 'UserController@invites');
Route::get('/premium', 'UserController@premium');
Route::post('/user_report', 'UserController@user_report');
Route::post('/user_recommend', 'UserController@user_recommend');
Route::post('/user_premium', 'UserController@user_premium');
Route::get('/single-user/{id}', 'UserController@user');
Route::post('/send_push', 'UserController@send_push');

Route::group(['middleware' => ['auth']], function () {
	Route::get('/logout' , 'Auth\LoginController@logout');
});

// card
Route::resource('card', 'CardController');


/*
|--------------------------------------------------------------------------
| Admin Authentication Routes
|--------------------------------------------------------------------------
*/

Route::group(['prefix' => 'admin'], function () {
  Route::get('/', 'AdminAuth\LoginController@showLoginForm');		
  Route::get('/login', 'AdminAuth\LoginController@showLoginForm');
  Route::post('/login', 'AdminAuth\LoginController@login');
  Route::post('/logout', 'AdminAuth\LoginController@logout');

  Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm');
  Route::post('/register', 'AdminAuth\RegisterController@register');

  Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail');
  Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset');
  Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm');
  Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
	
  // Route::group(['middleware' => ['admin']], function () {
	
  // });

});


Route::post('/usercredentials', 'UserController@verifyCredentials');
Route::post('/check-refercode', 'UserController@verifyRefercode');


Route::get('/pay-new', 'UserController@pay_new');
/*oute::get('/pay-new', function () {
   return view('payment-new');
});*/

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Route;

use App\User;
use App\UserPremium;
use App\UserPreferences;
use App\Settings;
use App\Transactions;
use App\Notifications;

use App\Http\Controllers\UserApiController;

use Setting;
use Redirect;
use Auth;
use Exception;
use Mail;
use DateTime;
use Carbon;


class UserController extends Controller
{
	protected $UserAPI;

	/**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(UserApiController $UserAPI)
    {
        $this->middleware('auth', ['except' => ['verifyCredentials','verifyRefercode']]);
        $this->UserAPI = $UserAPI;
    }

    /**
     * Show the Profile dashboard.
     *
     * @return \Illuminate\Http\Response
     */    
    public function home()
    { 
        $UserPreferences = UserPreferences::where('user_id',Auth::id())->first();
        if($UserPreferences){
            return Redirect('/dashboard');
        }else{
            return Redirect('/discover_settings');
        }

        //$user=$data['user'];
        //$user_images=$data['user_images'];
        return view('view_profile',compact('user'));
    }

    /**
     * Show the Profile dashboard.
     *
     * @return \Illuminate\Http\Response
     */    
    public function viewProfile(Request $request)
    { 
        $data = $this->UserAPI->getProfile($request); 
        $user=$data['user'];
        $interest=$data['interest'];
        $user_premium=$data['user_premium'];
        return view('view_profile',compact('user','interest','user_premium'));
    }

    /**
     * Edit the Profile dashboard.
     *
     * @return \Illuminate\Http\Response
     */    
    public function editProfile(Request $request)
    {	
        $data = $this->UserAPI->getProfile($request); 
        $user=$data['user'];
        $interests=$data['interest'];
        return view('edit_profile',compact('user','interests'));
    }
    /**
     * Update profile.
     *
     * @return \Illuminate\Http\Response
     */
    public function updateProfile(Request $request)
    {
        return $this->UserAPI->updateProfile($request);
    }
    /**
     * Matches listuse
     *
     * @return \Illuminate\Http\Response
     */
    public function matches(Request $request)
    {
        $user=Auth::user();
        $user['user_premium'] = UserPremium::with('premium')->where('user_id',Auth::id())->orderBy('id','desc')->first(); 
        $match_lists = $this->UserAPI->matchList($request);
        //dd(Auth::user()->id);
       //dd($match_lists);
        return view('matches',compact('user','match_lists'));
    }
    /**
     * Discover settings
     *
     * @return \Illuminate\Http\Response
     */
    public function discover_settings(Request $request)
    { 
        $discover_settings = $this->UserAPI->get_discover_settings($request);   
        $user=Auth::user();
        $user['user_premium'] = UserPremium::with('premium')->where('user_id',Auth::id())->orderBy('id','desc')->first(); 
        $user_preferences = UserPreferences::where('user_id',Auth::id())
                            ->orderBy('id','desc')
                            ->first();
        $latitude  = $user_preferences['latitude']; 
        $longitude = $user_preferences['longitude'];
        $selected_country = '';
        if(count($user_preferences['address'])!=0)
        {   
            $user_preferences_address=json_encode($user_preferences['address']);
            if(is_array($user_preferences_address)){
                foreach($user_preferences_address as $key => $val){
                    if($val->latitude==$latitude && $val->longitude == $longitude){
                        $selected_country = $val->country;
                    }
                }
            }
            /*$geocode=file_get_contents("https://maps.googleapis.com/maps/api/geocode/json?key=".Setting::get('map_key','AIzaSyDDCQMW-zn7-60euM-r8eeF15AIjs8oDfs') ."&latlng=".$latitude.",".$longitude."&sensor=false");
            $output_deals = json_decode($geocode);
            $selected_country = '';
            if(count($output_deals->results)!= ''){
                  $selected_country =$output_deals->results[0]->formatted_address; 
                // $selected_country =$output_deals->results[6]->address_components[4]->long_name;  
            }*/
        }
        return view('discover_settings',compact('discover_settings','user','selected_country'));
    }
    /**
     * Update Discover settings
     *
     * @return \Illuminate\Http\Response
     */
    public function update_discover_settings(Request $request)
    {    //return $request->all();
        return $this->UserAPI->update_discover_settings($request);
    }
    /**
     * Who likes me
     *
     * @return \Illuminate\Http\Response
     */
    public function who_likes_me(Request $request)
    {
        $user=Auth::user();
        $user['user_premium'] = UserPremium::with('premium')->where('user_id',Auth::id())->orderBy('id','desc')->first();
        $who_likes_me = $this->UserAPI->whoLikesMe($request);
        //dd($who_likes_me);
        return view('who_likes_me',compact('user','who_likes_me'));
    }
    /**
     * Chat list.
     *
     * @return \Illuminate\Http\Response
     */
    public function chat(Request $request)
    {        
        //$chat_users = $this->UserAPI->chat_list($request);
        $chat_users = $this->UserAPI->matchList($request); 
        //dd($chat_users);
        $user=Auth::user();
        $user['user_premium'] = UserPremium::with('premium')->where('user_id',Auth::id())->orderBy('id','desc')->first(); 
        return view('chat_list',compact('chat_users','user'));
    }
    /**
     * Chat User.
     *
     * @return \Illuminate\Http\Response
     */
    public function chat_user(Request $request)
    {        
        //$chat_users = $this->UserAPI->chat_user(); 
        $sender=User::with('user_images')->where('id',$request->id)->first();
        $user=Auth::user();
        $user['user_premium'] = UserPremium::with('premium')->where('user_id',Auth::id())->orderBy('id','desc')->first(); 
        return view('chat_user',compact('user','sender'));
    }
    /**
     * Help list.
     *
     * @return \Illuminate\Http\Response
     */

    /*public function help(Request $request)
    {
        $user=Auth::user();
        $user['user_premium'] = UserPremium::with('premium')->where('user_id',Auth::id())->orderBy('id','desc')->first(); 
        return view('help',compact('user'));
    }*/

    /**
     * Find Matches
     *
     * @return \Illuminate\Http\Response
     */
    public function find_matches(Request $request)
    {
        // dd($request);
        $user=Auth::user();
       // dd($user); 
        $user['user_premium'] = UserPremium::with('premium')->where('user_id',Auth::id())->orderBy('id','desc')->first();
        // dd($user['user_premium']); 
       
        //date format
        $reset_date = strtotime($user['user_premium']['reset_date']);
        $data = $this->UserAPI->findMatch($request);
        $find_matchs =$data['find_match'];
        $superlike_reach =$data['superlike_reach'];
        $superlike_count=$data['superlike_count'];
        $today_like_reach = $data['today_like_reach'];
        $like_count = $data['user_like_count'];
        $skip_pre = $data['skip_pre'];
        $matches = $this->UserAPI->matchList($request);
        // dd($matches);
        // dd($find_matchs);
        return view('find_matches',compact('user','find_matchs','matches','superlike_reach','superlike_count','today_like_reach','like_count','skip_pre','reset_date'));
    } 

    public function pay_new(Request $request){
        $user=Auth::user(); 
        $user['user_premium'] = UserPremium::with('premium')->where('user_id',Auth::id())->orderBy('id','desc')->first();

        return view('payment-new', compact('user'));
    }   
    /**
     * Find Matches
     *
     * @return \Illuminate\Http\Response
     */
    public function map_view(Request $request)
    {
        $user=Auth::user();  
        $user['user_premium'] = UserPremium::with('premium')->where('user_id',Auth::id())->orderBy('id','desc')->first();       
        $data = $this->UserAPI->findMatch($request);
        $find_matchs =$data['find_match'];
        $find_location =$find_matchs;
       // dd($find_location);
        $superlike_reach =$data['superlike_reach'];
        $superlike_count=$data['superlike_count'];
        $matches = $this->UserAPI->matchList($request);
        //dd($find_matchs);
        return view('map_view',compact('user','find_matchs','matches','superlike_reach','superlike_count'));
    }
    /**
     * Like
     *
     * @return \Illuminate\Http\Response
     */
    public function likes(Request $request)
    {
        
        $user=Auth::user();
        $likes = $this->UserAPI->likes($request); 
        return $likes;
    }

    public function update_notification(Request $request) {

        $notification = Notifications::where('user_id',$request->user_id)->where('notifier_id',$request->notifier_id)->update(['read' => 1]);

        if($request->ajax()) {

            return response()->json(['success' => 200,'notification' => $notification]);
        }  
    }
    /**
     * Like
     *
     * @return \Illuminate\Http\Response
     */
    public function skip(Request $request)
    {
        $likes = $this->UserAPI->skip($request); 
        return $likes;
    }
    /**
     * update_who_likes_me
     *
     * @return \Illuminate\Http\Response
     */
    public function update_likes(Request $request)
    {
        $user=Auth::user();
        $likes = $this->UserAPI->update_likes($request); 
        return $likes;
    }
    /**
     * Single_user
     *
     * @return \Illuminate\Http\Response
     */
    public function single_user(Request $request)
    {
        //$user=Auth::user();

resources/views/admin/users/create.blade.php
@extends('admin.layout.base')

@section('title', 'Add User ')


@section('content')


<link href="{{ asset('design/css/intlTelInput.css') }}" rel="stylesheet">  
<!-- Bootstrap Datepicker CSS -->
<!-- <link href="{{asset('design/css/bootstrap-datepicker.min.css')}}" rel="stylesheet"> -->
<script src="{{asset('design/js/intlTelInput.min.js')}}"></script>
<script src="{{asset('design/js/intlTelInput-jquery.min.js')}}"></script>
<!-- Bootstrap Datepicker JS -->
<!-- <script src="{{asset('design/js/bootstrap-datepicker.min.js')}}"></script> -->

<div class="content-area py-1">
    <div class="container-fluid">
    	<div class="box box-block bg-white">
            <a href="{{ route('admin.user.index') }}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> Back</a>

			<h5 style="margin-bottom: 2em;">Add User</h5>

            <form class="form-horizontal" action="{{route('admin.user.store')}}" method="POST" enctype="multipart/form-data" role="form">
            	{{csrf_field()}}
				<div class="form-group row">
					<label for="first_name" class="col-xs-12 col-form-label">First Name</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" value="{{ old('first_name') }}" name="first_name" required id="first_name" placeholder="First Name">
					</div>
				</div>

				<div class="form-group row">
					<label for="last_name" class="col-xs-12 col-form-label">Last Name</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" value="{{ old('last_name') }}" name="last_name" required id="last_name" placeholder="Last Name">
					</div>
				</div>

				<div class="form-group row">
					<label for="email" class="col-xs-12 col-form-label">Email</label>
					<div class="col-xs-10">
						<input class="form-control" type="email" required name="email" value="{{old('email')}}" id="email" placeholder="Email">
					</div>
				</div>

				<div class="form-group row">
					<label for="dob" class="col-xs-12 col-form-label">DOB</label>
					<div class="col-xs-10">
						<input class="form-control datepicker" type="date" required name="dob" value="" id="dob" placeholder="DOB" data-provide="datepicker">
					</div>
				</div>

				<div class="form-group row">
					<label for="gender" class="col-xs-12 col-form-label">Gender</label>
					<div class="col-xs-10">
						<!-- <input class="form-control" type="text" required name="dob" value="{{old('email')}}" id="dob" placeholder="Email" data-provide="datepicker"> -->
						<select name="gender" class="form-control">
							<option value="">Choose Gender</option>
							<option value="male">Male</option>
							<option value="female">Female</option>
							<option value="other">Other</option>
						</select>
					</div>
				</div>

<!-- 				<div class="form-group row">
					<label for="email" class="col-xs-12 col-form-label">Email</label>
					<div class="col-xs-10">
						<input class="form-control" type="email" required name="email" value="{{old('email')}}" id="email" placeholder="Email">
					</div>
				</div> -->

				<div class="form-group row">
					<label for="password" class="col-xs-12 col-form-label">Password</label>
					<div class="col-xs-10">
						<input class="form-control" type="password" name="password" id="password" placeholder="Password">
					</div>
				</div>

				<div class="form-group row">
					<label for="password_confirmation" class="col-xs-12 col-form-label">Password Confirmation</label>
					<div class="col-xs-10">
						<input class="form-control" type="password" name="password_confirmation" id="password_confirmation" placeholder="Re-type Password">
					</div>
				</div>

				<div class="form-group row">
					<label for="picture" class="col-xs-12 col-form-label">Picture</label>
					<div class="col-xs-10">
						<input type="file" accept="image/*" name="picture" class="dropify form-control-file" id="picture" aria-describedby="fileHelp">
					</div>
				</div>

				<div class="form-group row" style ="padding-bottom:50px;">
					<label for="mobile" class="col-xs-12 col-form-label">Mobile</label>
					<!-- <div class="col-xs-2">
						<input class="form-control" value="" name="country_code" id="country_code" placeholder="">
					</div> -->
					<div class="col-xs-12">
						<input class="form-control" style = "padding-right:795px";  value="" name="mobile" id="mobile" placeholder="Mobile">
					</div>
				</div>
				@if(\Setting::get('referal_status') =='on')
                    <!-- <div class="form-group row">
                        <label for="install_code" class="col-xs-12 col-form-label">Referral code (optional)</label>
                        <input type="text" id="install_code" name="install_code" class="form-control" placeholder="Referral code" onblur="checkrefercode(this.id)" value="{{Session::get('refercode')}}">
                    </div>
                    <div class="col-md-12" style="padding-bottom: 10px;" id="refercode_verfication"></div> -->
                @endif
                <input type="hidden" name="latitude" id="latitude_location" value="13.05298479">
                <input type="hidden" name="longitude" id="longitude_location" value="80.2488487">
				<div class="form-group row">
					<label for="zipcode" class="col-xs-12 col-form-label"></label>
					<div class="col-xs-10">
						<button type="submit" class="btn btn-primary">Add User</button>
						<a href="{{route('admin.user.index')}}" class="btn btn-default">Cancel</a>
					</div>
				</div>
			</form>
		</div>
    </div>
</div>

@endsection
@section('scripts')

<script>
<!-- For Mobile Details!-->
	//For mobile number with date
	var input = document.querySelector("#mobile");
        window.intlTelInput(input,({
            // separateDialCode:true,
        }));
        $(".country-name").click(function(){
            var myVar = $(this).closest('.country').find(".dial-code").text();
            $('#mobile').val(myVar);

		});

    function checkrefercode(id){ //alert(id);
            var refercode = document.getElementById(id).value; //alert(refercode);
            $.post("{{url('/check-refercode')}}",{ _token: '{{csrf_token()}}', refercode : refercode })
            .done(function(data){ 
                $('#refercode_verfication').html('');
            })
            .fail(function(xhr, status, error) {
                console.log(error);
                $('#'+id).val("");
                $('#refercode_verfication').html('Invalid Refercode');
             });

    }
</script>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layout.base')

@section('title', 'Update User ')
@section('content')

<div class="content-area py-1">
    <div class="container-fluid">
    	<div class="box box-block bg-white">
    	    <a href="{{ route('admin.user.index') }}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> Back</a>

			<h5 style="margin-bottom: 2em;">Update User</h5>

            <form class="form-horizontal" action="{{route('admin.user.update', $user->id )}}" method="POST" enctype="multipart/form-data" role="form">
            	{{csrf_field()}}
            	<input type="hidden" name="_method" value="PATCH">
				<div class="form-group row">
					<label for="first_name" class="col-xs-2 col-form-label">First Name</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" value="{{ $user->first_name }}" name="first_name" required id="first_name" placeholder="First Name">
					</div>
				</div>

				<div class="form-group row">
					<label for="last_name" class="col-xs-2 col-form-label">Last Name</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" value="{{ $user->last_name }}" name="last_name" required id="last_name" placeholder="Last Name">
					</div>
				</div>


				<div class="form-group row">
					
					<label for="picture" class="col-xs-2 col-form-label">Picture</label>
					<div class="col-xs-10">
					@if(isset($user->picture))
                    	<img style="height: 90px; margin-bottom: 15px; border-radius:2em;" src="{{$user->picture}}">
                    @endif
						<input type="file" accept="image/*" name="picture" class="dropify form-control-file" id="picture" aria-describedby="fileHelp">
					</div>
				</div>

				<div class="form-group row">
					<label for="mobile" class="col-xs-2 col-form-label">Mobile</label>
					<div class="col-xs-10">
						<input class="form-control" type="number" value="{{ $user->mobile }}" name="mobile" required id="mobile" placeholder="Mobile">
					</div>
				</div>

				<div class="form-group row">
					<label for="zipcode" class="col-xs-2 col-form-label"></label>
					<div class="col-xs-10">
						<button type="submit" class="btn btn-primary">Update user</button>
						<a href="{{route('admin.user.index')}}" class="btn btn-default">Cancel</a>
					</div>
				</div>
			</form>
		</div>
    </div>
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layout.base')

@section('title', 'Users ')

@section('content')

    <div class="content-area py-1">
        <div class="container-fluid">
            
            <div class="box box-block bg-white">
                @if(Setting::get('demo_mode') == 1)
                <div class="col-md-12" style="height:50px;color:red;">
                            ** Demo Mode : @lang('user.admin.demomode')
                </div>
                @endif
                <h5 class="mb-1">Users
                    @if(Setting::get('demo_mode', 0) == 1)
                    <span class="pull-right">(*personal information hidden in demo)</span>
                    @endif 
                </h5>
                
                <form class="form-inline" href="{{url('admin/user')}}">
                    <div class="form-group mb-2">
                        <label for="allsearch" class="sr-only">Search</label>
                        <input type="text" name="q" class="form-control-plaintext" id="allsearch" value="{{Request::get('q')}}" placeholder="Search..">
                    </div>
                    <!-- <div class="form-group mx-sm-3 mb-2">
                        <label for="premium" class="sr-only">User Type</label>
                        <select name="premium" class="form-control" id="premium" >
                            <option>Select</option>
                            <option value="yes" @if(Request::get('premium')=='yes') selected @endif  >Premium</option>
                            <option value="no" @if(Request::get('premium')=='no') selected @endif >Normal</option>
                        </select>
                    </div> -->
                    <button type="submit" class="btn btn-primary mb-2">Search</button>
                    <button type="reset" class="btn btn-primary mb-2" onClick="window.location.reload()"  >Reset</button>

                    <a href="{{ route('admin.user.create') }}" style="margin-left: 1em;" class="btn btn-primary pull-right mb-2"><i class="fa fa-plus"></i> Add New User</a>
                </form>
                
                
                <table class="table table-striped table-bordered dataTable" id="">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Email</th>
                            <th>Mobile</th>
                            <th>Wallet Amount</th>
                            @if( Setting::get('demo_mode') == 0)
                            <th>Action</th>
                            @endif
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $index => $user)
                        <tr>
                            <td>{{$index + 1}}</td>
                            <td>{{$user->first_name}}</td>
                            <td>{{$user->last_name}}</td>
                            @if(Setting::get('demo_mode', 0) == 1)
                            <td>{{ substr($user->email, 0, 3).'****'.substr($user->email, strpos($user->email, "@")) }}</td>
                            @else
                            <td>{{$user->email}}</td>
                            @endif
                            @if(Setting::get('demo_mode', 0) == 1)
                            <td>+919876543210</td>
                            @else
                            <td>{{$user->mobile}}</td>
                            @endif
                            <td>{{currency($user->wallet_balance)}}</td>
                            @if( Setting::get('demo_mode') == 0)
                            <td>
                                <form action="{{ route('admin.user.destroy', $user->id) }}" method="POST">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="DELETE">
                                    <!-- <a href="{{ url('user.request', $user->id) }}" class="btn btn-info"><i class="fa fa-search"></i> History</a> -->
                                    <a href="{{ route('admin.user.edit', $user->id) }}" class="btn btn-info"><i class="fa fa-pencil"></i> Edit</a>
                                    <button class="btn btn-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash"></i> Delete</button>
                                </form>
                            </td>
                            @endif
                        </tr>
                    @endforeach
                    </tbody>
                    
                </table>
                {{ $users->appends(request()->input())->links() }}
            </div>
            
        </div>
    </div>
@endsection
@section('styles')
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
@endsection
@section('scripts')
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script> -->
@endsection