routes/admin.php
<?php
 Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return Redirect('admin/dashboard');
});

Route::get('/dashboard', 'AdminController@dashboard');

//Chat
Route::get('/chat', 'AdminController@chat');
Route::post('/chat', 'AdminController@chat');	
Route::post('/user_friends', 'AdminController@user_friends');

//Push
Route::get('/push', 'AdminController@push');
Route::post('/push', 'AdminController@send_push');

//User report
Route::get('/user-report', 'AdminController@user_report');
Route::post('/user-block/{id}', 'AdminController@user_block');

//Payment
Route::get('user-premium', 'AdminController@user_premium');
Route::get('user-transaction', 'AdminController@user_transaction');
Route::get('admin-transaction', 'AdminController@admin_transaction');

//Resource
Route::resource('user', 	'Resource\UserResource');
Route::resource('interest', 	'Resource\InterestResource');
Route::resource('premium', 	'Resource\PremiumResource');

//Settings
Route::get('/settings', 'AdminController@adminSettings');
Route::post('/settings_store', 'AdminController@settings_store');

Route::get('/static_pages', 'AdminController@static_pages');
Route::post('/static_update', 'AdminController@static_update');

//Accounts
Route::get('/profile', 'AdminController@profile');
Route::post('/profile_update', 'AdminController@profile_update');

Route::get('/password', 'AdminController@password');
Route::post('/password_update', 'AdminController@password_update');

//Matches
Route::get('/matches', 'AdminController@user_matches');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('/otp', 'Auth\RegisterController@OTP');
Route::get('/', function () {
    //return view('welcome');
    $refercode=@$_GET['refercode'];
    Session::put('refercode',$refercode);
    return Redirect('/login');
});
/*Route::get('/home', function () {
    //return view('welcome');
    return Redirect('/dashboard');
});*/

//Static pages


Route::get('/clearconfig', function () {
    Artisan::call('config:clear');
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('config:cache');
    Artisan::call('view:clear');
});


Route::get('privacy', function () {
	$user=Auth::user();
	if($user)$user=$user;
	else $user=array();
    return view('privacy',compact('user'));
});
Route::get('terms', function () {
    $user=Auth::user();
	if($user)$user=$user;
	else $user=array();
    return view('terms',compact('user'));
});

Route::get('help', function () {
    
    $user=Auth::user();
    if($user)
      $user=$user;
    else 
      $user=array();
    return view('help',compact('user'));
});

// Route::get('contactus', function () {
//     $user=Auth::user();
// 	if($user)$user=$user;
// 	else $user=array();
//     return view('contactus',compact('user'));
// });

Route::get('testpush', 'SendPushNotification@testpush');

Auth::routes();

Route::group(['namespace' => 'Auth'], function() {
Route::post('/password/reset', 'ResetPasswordController@reset');
});

//Social login integration
Route::get('auth/facebook', 'Auth\SocialLoginController@redirectToFaceBook');
Route::get('auth/facebook/callback', 'Auth\SocialLoginController@handleFacebookCallback');
Route::get('auth/google', 'Auth\SocialLoginController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\SocialLoginController@handleGoogleCallback');
Route::get('auth/linkedin', 'Auth\SocialLoginController@redirectToLinkedin');
Route::get('auth/linkedin/callback', 'Auth\SocialLoginController@handleLinkedinCallback');
Route::post('account/kit', 'Auth\SocialLoginController@account_kit')->name('account.kit');

Route::get('/home', 'UserController@home');
Route::get('/dashboard', 'UserController@find_matches');
Route::get('/mapview', 'UserController@map_view');
Route::get('/profile', 'UserController@viewProfile');
Route::get('/editprofile', 'UserController@editProfile');
Route::post('/editprofile', 'UserController@updateProfile');
//ContactUs Details
Route::get('contactus', 'UserController@contactus');

Route::get('/matches', 'UserController@matches');
Route::get('/discover_settings', 'UserController@discover_settings');
Route::post('/discover_settings', 'UserController@update_discover_settings');
Route::get('/who_likes_me', 'UserController@who_likes_me');
Route::get('/chat', 'UserController@chat');
Route::get('/chat_user/{id}', 'UserController@chat_user');
//Route::get('/help', 'UserController@help');
Route::post('/likes' , 'UserController@likes');
Route::post('/update/new/notification' ,'UserController@update_notification');
Route::post('/skip' , 'UserController@skip');
Route::post('/update_likes' , 'UserController@update_likes');
Route::post('/single_user' , 'UserController@single_user');
Route::get('/payments', 'UserController@payment');
Route::post('/add_money', 'UserController@add_money');
Route::post('/payment_process', 'UserController@payment_process');
Route::get('/transaction_history', 'UserController@transaction_history');
Route::get('/notifications', 'UserController@notifications');
Route::get('/invites', 'UserController@invites');
Route::get('/premium', 'UserController@premium');
Route::post('/user_report', 'UserController@user_report');
Route::post('/user_recommend', 'UserController@user_recommend');
Route::post('/user_premium', 'UserController@user_premium');
Route::get('/single-user/{id}', 'UserController@user');
Route::post('/send_push', 'UserController@send_push');

Route::group(['middleware' => ['auth']], function () {
	Route::get('/logout' , 'Auth\LoginController@logout');
});

// card
Route::resource('card', 'CardController');


/*
|--------------------------------------------------------------------------
| Admin Authentication Routes
|--------------------------------------------------------------------------
*/

Route::group(['prefix' => 'admin'], function () {
  Route::get('/', 'AdminAuth\LoginController@showLoginForm');		
  Route::get('/login', 'AdminAuth\LoginController@showLoginForm');
  Route::post('/login', 'AdminAuth\LoginController@login');
  Route::post('/logout', 'AdminAuth\LoginController@logout');

  Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm');
  Route::post('/register', 'AdminAuth\RegisterController@register');

  Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail');
  Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset');
  Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm');
  Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
	
  // Route::group(['middleware' => ['admin']], function () {
	
  // });

});


Route::post('/usercredentials', 'UserController@verifyCredentials');
Route::post('/check-refercode', 'UserController@verifyRefercode');


Route::get('/pay-new', 'UserController@pay_new');
/*oute::get('/pay-new', function () {
   return view('payment-new');
});*/

resources/views/admin/include/footer.blade.php
<!-- Footer -->
<footer class="footer">
	<div class="container-fluid">
		<div class="row text-xs-center">
			<div class="col-sm-4 text-sm-left mb-0-5 mb-sm-0">
				2018 © {{Setting::get('sitename','MyDate')}}
			</div>
		</div>
	</div>
</footer>

resources/views/admin/include/header.blade.php
<!-- Header -->
<div class="site-header">
	<nav class="navbar navbar-light">
		<div class="navbar-left">
			<a class="navbar-brand" href="{{url('admin/dashboard')}}">
				<?php $site_logo = Setting::get('logo'); ?>
				<div class="logo" style="background: url({{$site_logo}}) no-repeat;background-size: contain;filter: invert(100%);"></div>
			</a>
			<div class="toggle-button dark sidebar-toggle-first float-xs-left hidden-md-up">
				<span class="hamburger"></span>
			</div>
			<div class="toggle-button-second dark float-xs-right hidden-md-up">
				<i class="ti-arrow-left"></i>
			</div>
			<div class="toggle-button dark float-xs-right hidden-md-up" data-toggle="collapse" data-target="#collapse-1">
				<span class="more"></span>
			</div>
		</div>
		<div class="navbar-right navbar-toggleable-sm collapse" id="collapse-1">
			<div class="toggle-button light sidebar-toggle-second float-xs-left hidden-sm-down">
				<span class="hamburger"></span>
			</div>

			<ul class="nav navbar-nav">
				<li class="nav-item hidden-sm-down">
					<a class="nav-link toggle-fullscreen" href="#">
						<i class="ti-fullscreen"></i>
					</a>
				</li>
			</ul>
			
			<ul class="nav navbar-nav float-md-right">
				<li class="nav-item dropdown hidden-sm-down">
					<a href="#" data-toggle="dropdown" aria-expanded="false">
						<span class="avatar box-32">
							<img src="" alt="">
						</span>
					</a>
					<div class="dropdown-menu dropdown-menu-right animated fadeInUp">
						<a class="dropdown-item" href="#">
							<i class="ti-user mr-0-5"></i> Profile
						</a>
						<a class="dropdown-item" href="#">
							<i class="ti-settings mr-0-5"></i> Change Password
						</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="#"><i class="ti-help mr-0-5"></i> Help</a>
						<a class="dropdown-item" href="{{ url('/admin/logout') }}"
                            onclick="event.preventDefault();
                                     document.getElementById('logout-form').submit();"><i class="ti-power-off mr-0-5"></i> Sign out</a>
					</div>
				</li>
			</ul>

		</div>
	</nav>
</div>

resources/views/admin/include/nav.blade.php
<div class="site-sidebar">
	<div class="custom-scroll custom-scroll-light">
		<ul class="sidebar-menu">
			<li class="menu-title">Main</li>
			<li>
				<a href="{{url('admin/dashboard')}}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-anchor"></i></span>
					<span class="s-text">Dashboard</span>
				</a>
			</li>
			<li>
				<a href="{{url('admin/chat')}}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-comments"></i></span>
					<span class="s-text">Chat View</span>
				</a>
			</li>
			
			<li class="menu-title">Members</li>
			<li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-crown"></i></span>
					<span class="s-text">Users</span>
				</a>
				<ul>
					<li><a href="{{route('admin.user.index')}}">User List</a></li>
					<li><a href="{{route('admin.user.create')}}">Add New User</a></li>
				</ul>
			</li>
			<li class="with-sub">
				<a href="javascript:void(0)" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-palette"></i></span>
					<span class="s-text">Interests</span>
				</a>
				<ul>
					<li><a href="{{route('admin.interest.index')}}">Interest List</a></li>
					<li><a href="{{route('admin.interest.create')}}">Add New Interest</a></li>
				</ul>
			</li>
			<li class="menu-title">Subscription and Payments</li>
			<li class="with-sub">
				<a href="#" class="waves-effect  waves-light">
					<span class="s-caret"><i class="fa fa-angle-down"></i></span>
					<span class="s-icon"><i class="ti-infinite"></i></span>
					<span class="s-text">Subscription</span>
				</a>
				<ul>
					<li><a href="{{route('admin.premium.index')}}">Subscription List</a></li>
					<li><a href="{{route('admin.premium.create')}}">Add New Subscription</a></li>
				</ul>
			</li>
			<li>
				<a href="{{url('admin/admin-transaction')}}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-money"></i></span>
					<span class="s-text">Admin Transactions</span>
				</a>
			</li>
			<li>
				<a href="{{url('admin/user-transaction')}}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-money"></i></span>
					<span class="s-text">User Transactions</span>
				</a>
			</li>
			<li>
				<a href="{{url('admin/user-premium')}}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-money"></i></span>
					<span class="s-text">User Subscription</span>
				</a>
			</li>
			<li class="menu-title">Matches</li>
			<li>
				<a href="{{url('admin/matches')}}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-heart"></i></span>
					<span class="s-text">Match Details</span>
				</a>
			</li>
			<li class="menu-title">Settings</li>
			<li>
				<a href="{{url('admin/settings')}}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-settings"></i></span>
					<span class="s-text">Setting</span>
				</a>
			</li>
			<li>
				<a href="{{url('admin/static_pages')}}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-smallcap"></i></span>
					<span class="s-text">Static Pages</span>
				</a>
			</li>
			<li class="menu-title">Others</li>
			<li>
				<a href="{{url('admin/push')}}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-smallcap"></i></span>
					<span class="s-text">Custom Push</span>
				</a>
			</li>
			<li>
				<a href="{{url('admin/user-report')}}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-user"></i></span>
					<span class="s-text">User Report</span>
				</a>
			</li>			
			<li class="menu-title">Account</li>
			<li>
				<a href="{{url('admin/profile')}}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-user"></i></span>
					<span class="s-text">Account Settings</span>
				</a>
			</li>
			<li>
				<a href="{{url('admin/password')}}" class="waves-effect  waves-light">
					<span class="s-icon"><i class="ti-exchange-vertical"></i></span>
					<span class="s-text">Change Password</span>
				</a>
			</li>
			<li class="compact-hide">
				<a href="{{ url('/admin/logout') }}"
                            onclick="event.preventDefault();
                                     document.getElementById('logout-form').submit();">
					<span class="s-icon"><i class="ti-power-off"></i></span>
					<span class="s-text">Logout</span>
                </a>

                <form id="logout-form" action="{{ url('/admin/logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
			</li>
			
		</ul>
	</div>
</div>