routes/admin.php
<?php
 Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return Redirect('admin/dashboard');
});

Route::get('/dashboard', 'AdminController@dashboard');

//Chat
Route::get('/chat', 'AdminController@chat');
Route::post('/chat', 'AdminController@chat');	
Route::post('/user_friends', 'AdminController@user_friends');

//Push
Route::get('/push', 'AdminController@push');
Route::post('/push', 'AdminController@send_push');

//User report
Route::get('/user-report', 'AdminController@user_report');
Route::post('/user-block/{id}', 'AdminController@user_block');

//Payment
Route::get('user-premium', 'AdminController@user_premium');
Route::get('user-transaction', 'AdminController@user_transaction');
Route::get('admin-transaction', 'AdminController@admin_transaction');

//Resource
Route::resource('user', 	'Resource\UserResource');
Route::resource('interest', 	'Resource\InterestResource');
Route::resource('premium', 	'Resource\PremiumResource');

//Settings
Route::get('/settings', 'AdminController@adminSettings');
Route::post('/settings_store', 'AdminController@settings_store');

Route::get('/static_pages', 'AdminController@static_pages');
Route::post('/static_update', 'AdminController@static_update');

//Accounts
Route::get('/profile', 'AdminController@profile');
Route::post('/profile_update', 'AdminController@profile_update');

Route::get('/password', 'AdminController@password');
Route::post('/password_update', 'AdminController@password_update');

//Matches
Route::get('/matches', 'AdminController@user_matches');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('/otp', 'Auth\RegisterController@OTP');
Route::get('/', function () {
    //return view('welcome');
    $refercode=@$_GET['refercode'];
    Session::put('refercode',$refercode);
    return Redirect('/login');
});
/*Route::get('/home', function () {
    //return view('welcome');
    return Redirect('/dashboard');
});*/

//Static pages


Route::get('/clearconfig', function () {
    Artisan::call('config:clear');
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('config:cache');
    Artisan::call('view:clear');
});


Route::get('privacy', function () {
	$user=Auth::user();
	if($user)$user=$user;
	else $user=array();
    return view('privacy',compact('user'));
});
Route::get('terms', function () {
    $user=Auth::user();
	if($user)$user=$user;
	else $user=array();
    return view('terms',compact('user'));
});

Route::get('help', function () {
    
    $user=Auth::user();
    if($user)
      $user=$user;
    else 
      $user=array();
    return view('help',compact('user'));
});

// Route::get('contactus', function () {
//     $user=Auth::user();
// 	if($user)$user=$user;
// 	else $user=array();
//     return view('contactus',compact('user'));
// });

Route::get('testpush', 'SendPushNotification@testpush');

Auth::routes();

Route::group(['namespace' => 'Auth'], function() {
Route::post('/password/reset', 'ResetPasswordController@reset');
});

//Social login integration
Route::get('auth/facebook', 'Auth\SocialLoginController@redirectToFaceBook');
Route::get('auth/facebook/callback', 'Auth\SocialLoginController@handleFacebookCallback');
Route::get('auth/google', 'Auth\SocialLoginController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\SocialLoginController@handleGoogleCallback');
Route::get('auth/linkedin', 'Auth\SocialLoginController@redirectToLinkedin');
Route::get('auth/linkedin/callback', 'Auth\SocialLoginController@handleLinkedinCallback');
Route::post('account/kit', 'Auth\SocialLoginController@account_kit')->name('account.kit');

Route::get('/home', 'UserController@home');
Route::get('/dashboard', 'UserController@find_matches');
Route::get('/mapview', 'UserController@map_view');
Route::get('/profile', 'UserController@viewProfile');
Route::get('/editprofile', 'UserController@editProfile');
Route::post('/editprofile', 'UserController@updateProfile');
//ContactUs Details
Route::get('contactus', 'UserController@contactus');

Route::get('/matches', 'UserController@matches');
Route::get('/discover_settings', 'UserController@discover_settings');
Route::post('/discover_settings', 'UserController@update_discover_settings');
Route::get('/who_likes_me', 'UserController@who_likes_me');
Route::get('/chat', 'UserController@chat');
Route::get('/chat_user/{id}', 'UserController@chat_user');
//Route::get('/help', 'UserController@help');
Route::post('/likes' , 'UserController@likes');
Route::post('/update/new/notification' ,'UserController@update_notification');
Route::post('/skip' , 'UserController@skip');
Route::post('/update_likes' , 'UserController@update_likes');
Route::post('/single_user' , 'UserController@single_user');
Route::get('/payments', 'UserController@payment');
Route::post('/add_money', 'UserController@add_money');
Route::post('/payment_process', 'UserController@payment_process');
Route::get('/transaction_history', 'UserController@transaction_history');
Route::get('/notifications', 'UserController@notifications');
Route::get('/invites', 'UserController@invites');
Route::get('/premium', 'UserController@premium');
Route::post('/user_report', 'UserController@user_report');
Route::post('/user_recommend', 'UserController@user_recommend');
Route::post('/user_premium', 'UserController@user_premium');
Route::get('/single-user/{id}', 'UserController@user');
Route::post('/send_push', 'UserController@send_push');

Route::group(['middleware' => ['auth']], function () {
	Route::get('/logout' , 'Auth\LoginController@logout');
});

// card
Route::resource('card', 'CardController');


/*
|--------------------------------------------------------------------------
| Admin Authentication Routes
|--------------------------------------------------------------------------
*/

Route::group(['prefix' => 'admin'], function () {
  Route::get('/', 'AdminAuth\LoginController@showLoginForm');		
  Route::get('/login', 'AdminAuth\LoginController@showLoginForm');
  Route::post('/login', 'AdminAuth\LoginController@login');
  Route::post('/logout', 'AdminAuth\LoginController@logout');

  Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm');
  Route::post('/register', 'AdminAuth\RegisterController@register');

  Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail');
  Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset');
  Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm');
  Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
	
  // Route::group(['middleware' => ['admin']], function () {
	
  // });

});


Route::post('/usercredentials', 'UserController@verifyCredentials');
Route::post('/check-refercode', 'UserController@verifyRefercode');


Route::get('/pay-new', 'UserController@pay_new');
/*oute::get('/pay-new', function () {
   return view('payment-new');
});*/

app/Interest.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Interest extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'image'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'created_at'
    ];
}

resources/views/admin/interests/create.blade.php
@extends('admin.layout.base')

@section('title', 'Add Interest ')


@section('content')

<div class="content-area py-1">
    <div class="container-fluid">
    	<div class="box box-block bg-white">
            <a href="{{ route('admin.interest.index') }}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> Back</a>

			<h5 style="margin-bottom: 2em;">Add Interest</h5>

            <form class="form-horizontal" action="{{route('admin.interest.store')}}" method="POST" enctype="multipart/form-data" role="form">
            	{{csrf_field()}}
				<div class="form-group row">
					<label for="name" class="col-xs-12 col-form-label">Interest Name</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" value="{{ old('name') }}" name="name" required id="name" placeholder="Interest Name">
					</div>
				</div>

				<div class="form-group row">
					<label for="description" class="col-xs-12 col-form-label">Interest Description</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" value="{{ old('description') }}" name="description" id="description" placeholder="Interest Description">
					</div>
				</div>

				<div class="form-group row">
					<label for="image" class="col-xs-12 col-form-label">Interest Picture</label>
					<div class="col-xs-10">
						<input type="file" accept="image/*" name="image" class="dropify form-control-file" id="image" aria-describedby="fileHelp">
					</div>
				</div>

				<div class="form-group row">
					<label for="zipcode" class="col-xs-12 col-form-label"></label>
					<div class="col-xs-10">
						<button type="submit" class="btn btn-primary">Add Interest</button>
						<a href="{{route('admin.interest.index')}}" class="btn btn-default">Cancel</a>
					</div>
				</div>
			</form>
		</div>
    </div>
</div>

@endsection

resources/views/admin/interests/edit.blade.php
@extends('admin.layout.base')

@section('title', 'Update Interest ')
@section('content')

<div class="content-area py-1">
    <div class="container-fluid">
    	<div class="box box-block bg-white">
    	    <a href="{{ route('admin.interest.index') }}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> Back</a>

			<h5 style="margin-bottom: 2em;">Update Interest</h5>

            <form class="form-horizontal" action="{{route('admin.interest.update', $interest->id )}}" method="POST" enctype="multipart/form-data" role="form">
            	{{csrf_field()}}
            	<input type="hidden" name="_method" value="PATCH">
				<div class="form-group row">
					<label for="name" class="col-xs-2 col-form-label">Interest Name</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" value="{{ $interest->name }}" name="name" required id="name" placeholder="Interest Name">
					</div>
				</div>

				<div class="form-group row">
					<label for="description" class="col-xs-2 col-form-label">Interest Description</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" value="{{ $interest->description }}" name="description" required id="description" placeholder="Interest Description">
					</div>
				</div>


				<div class="form-group row">
					
					<label for="image" class="col-xs-2 col-form-label">Interest Image</label>
					<div class="col-xs-10">
					@if(isset($interest->image))
                    	<img style="height: 90px; margin-bottom: 15px; border-radius:2em;" src="{{$interest->image}}">
                    @endif
						<input type="file" accept="image/*" name="image" class="dropify form-control-file" id="image" aria-describedby="fileHelp">
					</div>
				</div>

				<div class="form-group row">
					<label for="zipcode" class="col-xs-2 col-form-label"></label>
					<div class="col-xs-10">
						<button type="submit" class="btn btn-primary">Update Interest</button>
						<a href="{{route('admin.interest.index')}}" class="btn btn-default">Cancel</a>
					</div>
				</div>
			</form>
		</div>
    </div>
</div>

@endsection

resources/views/admin/interests/index.blade.php
@extends('admin.layout.base')

@section('title', 'Interests')

@section('content')

    <div class="content-area py-1">
        <div class="container-fluid">
            
            <div class="box box-block bg-white">
                 @if(Setting::get('demo_mode') == 1)
                    <div class="col-md-12" style="height:50px;color:red;">
                                ** Demo Mode : @lang('user.admin.demomode')
                    </div>
                @endif
                <h5 class="mb-1">Interests
                @if(Setting::get('demo_mode', 0) == 1)
                    <span class="pull-right">(*personal information hidden in demo)</span>
                @endif 
                </h5>
                <a href="{{ route('admin.interest.create') }}" style="margin-left: 1em;" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Add New Interest</a>
                <table class="table table-striped table-bordered dataTable" id="table-2">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Interest Name</th>
                            <th>Interest Description</th>
                            <th>Interest Image</th>
                            @if( Setting::get('demo_mode') == 0)
                            <th>Action</th>
                            @endif
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($interests as $index => $interest)
                        <tr>
                            <td>{{$index + 1}}</td>
                            <td>{{$interest->name}}</td>
                            <td>{{$interest->description}}</td>
                            <td>{{$interest->image}}</td>
                            @if( Setting::get('demo_mode') == 0)
                            <td>
                                <form action="{{ route('admin.interest.destroy', $interest->id) }}" method="POST">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="DELETE">
                                    <!-- <a href="{{ url('interest.request', $interest->id) }}" class="btn btn-info"><i class="fa fa-search"></i> History</a> -->
                                    <a href="{{ route('admin.interest.edit', $interest->id) }}" class="btn btn-info"><i class="fa fa-pencil"></i> Edit</a>
                                    <button class="btn btn-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash"></i> Delete</button>
                                </form>
                            </td>
                            @endif
                        </tr>
                    @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Interest Name</th>
                            <th>Interest Description</th>
                            <th>Interest Image</th>
                            @if( Setting::get('demo_mode') == 0)
                            <th>Action</th>
                            @endif
                        </tr>
                    </tfoot>
                </table>
            </div>
            
        </div>
    </div>
@endsection

resources/views/admin/interests/interest-details.blade.php
@extends('admin.layout.base')

@section('title', 'User Details ')

@section('content')

    <div class="content-area py-1">
        <div class="container-fluid">
            <div class="box box-block bg-white">
            	<h4>@lang('main.user') Details</h4>
            	<div class="row">
            		<div class="col-md-12">
						<div class="box bg-white user-1">
						<?php $background = asset('admin/assets/img/photos-1/4.jpg'); ?>
							<div class="u-img img-cover" style="background-image: url({{$background}});"></div>
							<div class="u-content">
								<div class="avatar box-64">
									<img class="b-a-radius-circle shadow-white" src="{{$user->picture}}" alt="">
									<i class="status bg-success bottom right"></i>
								</div>
								<h5><a class="text-black" href="#">{{$user->first_name}} {{$user->last_name}}</a></h5>
								<p class="text-muted">Email : {{$user->email}}</p>
								<p class="text-muted">Mobile : {{$user->mobile}}</p>
								<p class="text-muted">Gender : {{$user->gender}}</p>
								<p class="text-muted">Wallet Balance : {{currency($user->wallet_balance)}}</p>
							</div>
						</div>
					</div>
            	</div>

            </div>
        </div>
    </div>

@endsection